name: Build Recomputer-Gateway Firmware

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 1'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [closed]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E apt-get -qq install clang file
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
      
      - name: Check disk usage before build
        run: df -h

      - name: Set up OpenWrt build environment
        run: |
          git submodule update --init --recursive
          cd openwrt && rm -r feeds.conf.default && cp ../feeds.conf.default feeds.conf.default
          cat feeds.conf.default

      - name: Update feeds
        run: cd openwrt && ./scripts/feeds update -a

      - name: Install feeds
        run: cd openwrt && ./scripts/feeds install -a

      - name: Initial configuration
        run: |
          cd openwrt && make defconfig
          rm -r .config && cp ../.config .config
          make defconfig
          cat .config

      - name: Build for recomputer-gateway
        run: |
          cd openwrt
          unset CI
          unset GITHUB_ACTIONS
          unset CONTINUOUS_INTEGRATION
          make -j$(nproc)
      
      - name: Upload recomputer-gateway artifacts
        uses: actions/upload-artifact@v4
        with:
          name: recomputer-gateway
          path: |
            ./openwrt/bin/targets/armsr/armv8/openwrt-armsr-armv8-generic-rootfs.tar.gz